name: build+check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run cmake --version
        shell: bash
        run: |
          VERSION=`cmake --version`
          echo $VERSION
      - name: build
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
      - name: check
        shell: bash
        run: |
          hello_world_application/_build/Hello
          solver_application/_build/Solver 1 100 5
          
